/** MCP `search_*` entity stem for list pages (PLAN §9). */
export const ENTITY_SEARCH: Record<string, string> = {
	customers: "customers",
	vendors: "vendors",
	invoices: "invoices",
	payments: "payments",
	bills: "bills",
	"bill-payments": "bill_payments",
	"sales-receipts": "sales_receipts",
	"credit-memos": "credit_memos",
	"refund-receipts": "refund_receipts",
	deposits: "deposits",
	transfers: "transfers",
	estimates: "estimates",
	"purchase-orders": "purchase_orders",
	"vendor-credits": "vendor_credits",
	purchases: "purchases",
	"journal-entries": "journal_entries",
	"time-activities": "time_activities",
	attachables: "attachables",
	accounts: "accounts",
	classes: "classes",
	departments: "departments",
};
