/** URL segment → internal entity stem for QBO list pages. */
export const ENTITY_SEARCH: Record<string, string> = {
	customers: "customers",
	vendors: "vendors",
	invoices: "invoices",
	payments: "payments",
	bills: "bills",
	"bill-payments": "bill_payments",
	"sales-receipts": "sales_receipts",
	"credit-memos": "credit_memos",
	"refund-receipts": "refund_receipts",
	deposits: "deposits",
	transfers: "transfers",
	estimates: "estimates",
	"purchase-orders": "purchase_orders",
	"vendor-credits": "vendor_credits",
	purchases: "purchases",
	"journal-entries": "journal_entries",
	"time-activities": "time_activities",
	attachables: "attachables",
	accounts: "accounts",
	classes: "classes",
	departments: "departments",
};

/** Intuit query language entity name for each stem (e.g. `Customer`, `BillPayment`). */
export const ENTITY_QBO_QUERY_ENTITY: Record<string, string> = {
	customers: "Customer",
	vendors: "Vendor",
	invoices: "Invoice",
	payments: "Payment",
	bills: "Bill",
	bill_payments: "BillPayment",
	sales_receipts: "SalesReceipt",
	credit_memos: "CreditMemo",
	refund_receipts: "RefundReceipt",
	deposits: "Deposit",
	transfers: "Transfer",
	estimates: "Estimate",
	purchase_orders: "PurchaseOrder",
	vendor_credits: "VendorCredit",
	purchases: "Purchase",
	journal_entries: "JournalEntry",
	time_activities: "TimeActivity",
	attachables: "Attachable",
	accounts: "Account",
	classes: "Class",
	departments: "Department",
};

/** Field used for optional text filter in `qbo.searchProxy` (Intuit query `where … like`). */
export const ENTITY_SEARCH_QUERY_KEY: Record<string, string> = {
	customers: "DisplayName",
	vendors: "DisplayName",
	employees: "DisplayName",
	invoices: "DocNumber",
	bills: "DocNumber",
	payments: "DocNumber",
	estimates: "DocNumber",
	sales_receipts: "DocNumber",
	credit_memos: "DocNumber",
	refund_receipts: "DocNumber",
	deposits: "DocNumber",
	transfers: "DocNumber",
	purchase_orders: "DocNumber",
	vendor_credits: "DocNumber",
	purchases: "DocNumber",
	journal_entries: "DocNumber",
	classes: "Name",
	departments: "Name",
	bill_payments: "DocNumber",
	time_activities: "Name",
};
